# action.yml
name: 'Post Logs to Splunk HEC'
description: 'Upload GitHub Workflow logs to Splunk HEC'
inputs:
  splunk-url:
    description: 'Full URL for Splunk HEC endpoint'
    required: true
  hec-token:
    description: 'Splunk HEC Token'
    required: true
  sourcetype:
    description: 'Splunk Sourcetype'
    default: 'github_workflow_log'
  source:
    description: 'Splunk source'
    default: 'github_workflow'
  workflowID:
    description: 'The Workflow name and Run number'
    default: $GITHUB_WORKFLOW+' \#'+$GITHUB_RUN_NUMBER
outputs:
  status:
    description: 'value is success/fail based on app inspect result'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.splunk-url }}
    - ${{ inputs.hec-token }}
    - ${{ inputs.sourcetype }}
    - ${{ inputs.source }}
    - ${{ inputs.workflowID }}
