name: Lint and App Inspect CLI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Forwarder
        run: |
          wget -O splunkforwarder-8.2.1-ddff1c41e5cf-Linux-x86_64.tgz 'https://d7wz6hmoaavd0.cloudfront.net/products/universalforwarder/releases/8.2.1/linux/splunkforwarder-8.2.1-ddff1c41e5cf-Linux-x86_64.tgz'
          tar xvzf splunkforwarder-8.2.1-ddff1c41e5cf-Linux-x86_64.tgz -C /opt
          /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd test1234
          /opt/splunkforwarder/bin/splunk add forward-server 18.237.122.160:9997 -auth 'admin:test1234'
          /opt/splunkforwarder/bin/splunk add forward-server 54.187.218.234:9997 -auth 'admin:test1234'
          /opt/splunkforwarder/bin/splunk restart
          /opt/splunkforwarder/bin/splunk add monitor "/home/runner/runners/*/_diag" -index github_workflow -auth 'admin:test1234'
          ls -al /home/runner/runners/2.280.2/_diag
          cat /opt/splunkforwarder/var/log/splunk/splunkd.log
          /opt/splunkforwarder/bin/splunk status
          /opt/splunkforwarder/bin/splunk list inputstatus


      - name: Install deps
        uses: CultureHQ/actions-yarn@master
        with:
          args: install

      - name: Lint
        uses: CultureHQ/actions-yarn@master
        with:
          args: lint

      - name: Build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build

      - name: Update Permissions
        run: |
          chmod +x ./.github/actions/appinspect_cli/entrypoint.sh

      - name: Update Version Number
        run: |
          old_str="X.Y.Z"
          new_str="1.0.0"
          sed -i "s/$old_str/$new_str/g" package.json
          sed -i "s/$old_str/$new_str/g" ./github_app_for_splunk/default/app.conf

      - name: Run App Inspect CLI
        uses: ./.github/actions/appinspect_cli
        with:
          app-path: github_app_for_splunk/
