name: Lint and App Inspect CLI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  inspect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        uses: CultureHQ/actions-yarn@master
        with:
          args: install

      - name: Lint
        uses: CultureHQ/actions-yarn@master
        with:
          args: lint

      - name: Build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build

      - name: Update Permissions
        run: |
          chmod +x ./.github/actions/appinspect_cli/entrypoint.sh

      - name: Update Version Number
        run: |
          old_str="X.Y.Z"
          new_str="1.0.0"
          sed -i "s/$old_str/$new_str/g" package.json
          sed -i "s/$old_str/$new_str/g" ./github_app_for_splunk/default/app.conf

      - name: Run App Inspect CLI
        uses: ./.github/actions/appinspect_cli
        with:
          app-path: github_app_for_splunk/

      - name: Prepare log files
        run: cat /home/runner/runners/2.280.3/_diag/pages/*.log > ./file.log

      - name: POST Workflow logs to Splunk
        uses: ./.github/actions/post_logs_to_splunk_hec
        with:
          splunk-url: http://54.189.34.108:8088/
          hec-token: ${{ secrets.HEC_TOKEN }}
