name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f ./github-audit-log-monitoring-add-on-for-splunk/requirements.txt ]; then pip install -r ./github-audit-log-monitoring-add-on-for-splunk/requirements.txt; fi
    - name: Test with nosetests
      run: |
        sed -i 's/from audit_log_entry/from .audit_log_entry/g' ./github-audit-log-monitoring-add-on-for-splunk/bin/audit_log.py
        sed -i 's/from audit_log/from .audit_log/g' ./github-audit-log-monitoring-add-on-for-splunk/bin/rest_client.py
        nosetests -vs
        sed -i 's/from .audit_log_entry/from audit_log_entry/g' ./github-audit-log-monitoring-add-on-for-splunk/bin/audit_log.py
        sed -i 's/from .audit_log/from audit_log/g' ./github-audit-log-monitoring-add-on-for-splunk/bin/rest_client.py
